/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const OrderListLazyImport = createFileRoute("/orderList")();
const OrderLazyImport = createFileRoute("/order")();
const CartLazyImport = createFileRoute("/cart")();
const IndexLazyImport = createFileRoute("/")();
const ProductIdLazyImport = createFileRoute("/product/$id")();

// Create/Update Routes

const OrderListLazyRoute = OrderListLazyImport.update({
  path: "/orderList",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/orderList.lazy").then((d) => d.Route));

const OrderLazyRoute = OrderLazyImport.update({
  path: "/order",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/order.lazy").then((d) => d.Route));

const CartLazyRoute = CartLazyImport.update({
  path: "/cart",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/cart.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const ProductIdLazyRoute = ProductIdLazyImport.update({
  path: "/product/$id",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/product_.$id.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/cart": {
      preLoaderRoute: typeof CartLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/order": {
      preLoaderRoute: typeof OrderLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/orderList": {
      preLoaderRoute: typeof OrderListLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/product/$id": {
      preLoaderRoute: typeof ProductIdLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CartLazyRoute,
  OrderLazyRoute,
  OrderListLazyRoute,
  ProductIdLazyRoute,
]);

/* prettier-ignore-end */
